
@base = http://localhost:8000/api/v1
@access = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExYjgyNzRiLTk5NDUtNGVlNi1iYzI3LWNiNmY3ZmJmNjEzNCIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsIm5hbWUiOiJ0ZXN0Iiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzI4MTYyOTIsImV4cCI6MTc3MjgxNzE5Mn0.JjXLS8fK21s4nJUnPODKq9xitDbCQWUdcE-1wj7CaMc
@refresh = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExYjgyNzRiLTk5NDUtNGVlNi1iYzI3LWNiNmY3ZmJmNjEzNCIsImlhdCI6MTc3MjUyNjA5NCwiZXhwIjoxNzczMTMwODk0fQ._EUwFkuH5atUuGUgMr7asCGq7LS7dE1ePr8NSTpNDos

## auth

### register

POST {{base}}/auth/register
content-type: application/json

{
    "name": "test",
    "email": "test@test.com",
    "password": "TEst@@1234"
}

### login

POST {{base}}/auth/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "TEst@@1234"
}


### me

GET {{base}}/auth/me
content-type: application/json
Authorization: Bearer {{access}}


### token

GET {{base}}/auth/token
content-type: application/json
Authorization: Bearer {{refresh}}


## permission

### create

POST {{base}}/permission
content-type: application/json
Authorization: Bearer {{access}}

{
    "role":"user",
    "resorce": "user",
    "value": true
}

# {
#     "role":"user",
#     "resorce": "user",
#     "action":"create",
#     "value":{
#         "type" :"not",
#         "leaf":{
#             "type":"leaf",
#             "ref": "user.role",
#             "op":"eq",
#             "value":"user"
#         }
#     }
# }

### all permission

GET {{base}}/permission
content-type: application/json
Authorization: Bearer {{access}}


### permission by id

GET {{base}}/permission/11e4b49f-04a6-4923-9327-e228d4ab77b2
content-type: application/json
Authorization: Bearer {{access}}


### update permission by id

PATCH {{base}}/permission/11e4b49f-04a6-4923-9327-e228d4ab77b2
content-type: application/json
Authorization: Bearer {{access}}

{
    "value": false
}