
@base = http://localhost:8000/api/v1
@access = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExYjgyNzRiLTk5NDUtNGVlNi1iYzI3LWNiNmY3ZmJmNjEzNCIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsIm5hbWUiOiJ0ZXN0Iiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzM2NjkwOTQsImV4cCI6MTc3MzY2OTk5NH0.YPPBLRJFueBtO61FS55hqda-NpKvyITd3Na5FNFoUd4
@refresh = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExYjgyNzRiLTk5NDUtNGVlNi1iYzI3LWNiNmY3ZmJmNjEzNCIsImlhdCI6MTc3MzQ2NjI1OSwiZXhwIjoxNzc0MDcxMDU5fQ.Lv1iNZU9BdVQ_VGKgK1AUdCS4LEti-fKejDdsh3sVE0

## auth

### register

POST {{base}}/auth/register
content-type: application/json

{
    "name": "test",
    "email": "test@test.com",
    "password": "TEst@@1234"
}

### login

POST {{base}}/auth/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "TEst@@1234"
}


### me

GET {{base}}/auth/me
content-type: application/json
Authorization: Bearer {{access}}


### token

GET {{base}}/auth/token
content-type: application/json
Authorization: Bearer {{refresh}}


## permission

### create

POST {{base}}/permission
content-type: application/json
Authorization: Bearer {{access}}

{
    "role":"user",
    "resorce": "user",
    "value": true
}

# {
#     "role":"user",
#     "resorce": "user",
#     "action":"create",
#     "value":{
#         "type" :"not",
#         "leaf":{
#             "type":"leaf",
#             "ref": "user.role",
#             "op":"eq",
#             "value":"user"
#         }
#     }
# }

### all permission

GET {{base}}/permission
content-type: application/json
Authorization: Bearer {{access}}


### permission by id

GET {{base}}/permission/11e4b49f-04a6-4923-9327-e228d4ab77b2
content-type: application/json
Authorization: Bearer {{access}}


### update permission by id

PATCH {{base}}/permission/11e4b49f-04a6-4923-9327-e228d4ab77b2
content-type: application/json
Authorization: Bearer {{access}}

{
    "value": false
}


### permission

GET {{base}}/permission/permission?role=user&resorce=user&action=create
content-type: application/json

### DELETE permission by id

DELETE {{base}}/permission/73106606-095c-4c81-bc92-56de77e6249c
content-type: application/json
Authorization: Bearer {{access}}


## post

### create

POST {{base}}/post
content-type: application/json
Authorization: Bearer {{access}}

{
    "title":"This is title",
    "slug": "this is slug",
    "content": "this is content",
    "desc": "this is desc"
}

### get all

GET {{base}}/post
content-type: application/json
Authorization: Bearer {{access}}


### get by slug

GET {{base}}/post/this-is-slug
content-type: application/json

### update by slug

PATCH {{base}}/post/this-is-slug
content-type: application/json
Authorization: Bearer {{access}}

{
    "title":"This is updated title"
}

### detete by slug

DELETE {{base}}/post/this-is-slug
content-type: application/json
Authorization: Bearer {{access}}

{
    "title":"This is updated title"
}
